; (define x 2)
(define (my-map proc lst)
(if (null? lst) (car lst) 
    (proc (car (cdr lst)))))
; (proc 1)
; (proc 2))))
(display (my-map (lambda (x) (+ x x)) '(1 2 3)))
; (display (if #t x 3))
; (define (func y) (+ 2 y))
; (display x)
; (display (func x))