(define (my-map proc lst) (map proc lst))
(display (my-map (lambda (x) (+ 1 x)) '(1 2 3)))
(display (if #f 
             (my-map (lambda (x) (+ 1 x)) '(1 2 3)) 
             (my-map (lambda (x) (+ 4 x)) '(1 2 3))))
            ; (define x 2)
(define (my-new-map proc lst) 
    (if (null? lst) '() 
        (cons (proc (car lst)) (my-new-map proc (cdr lst)))))
(display (my-new-map (lambda (x) (+ 7 x)) '(1 2 3)))
; ../src/examples/guile/hello-world.scm
; (proc 1)
; (proc 2))))
; (display (my-map (lambda (x) (+ x x)) '(1 2 3)))
; (display (my-map sqrt '(1 2 3)))
; (display (if #t x 3))
; (define (func y) (+ 2 y))
; (display x)
; (display (func x))