#!/bin/sh

set -e
ls -l /usr/bin/python*
virtualenv py3 --python=/usr/bin/python3.4
. py3/bin/activate
pip3 install -q meson

wget -O /tmp/ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.7.1/ninja-linux.zip
unzip -d py3/bin /tmp/ninja.zip

# build documentation
mkdir build
meson . build
ninja -C build doc

deactivate
rm -rf py3
