#!/bin/sh

set -e

virtualenv py3 --python=/usr/bin/python3.4
. py3/bin/activate
pip3 install -q meson

wget -O /tmp/ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.7.1/ninja-linux.zip
unzip -d py3/bin /tmp/ninja.zip

# build documentation
#meson . build
#ninja -C build doc
export MESON_SOURCE_ROOT=$(pwd)
export MESON_BUILD_ROOT=$MESON_SOURCE_ROOT/build
mkdir -p $MESON_BUILD_ROOT
cd $MESON_BUILD_ROOT
doxygen $MESON_SOURCE_ROOT/Doxyfile
cd -

deactivate
rm -rf py3
