#!/bin/sh

files=$(find . -type f -name "*.cc" -or -name "*.hh")

check() {
func=$1
#echo "Checking for $1... "
grep -H "$func" $files && echo "$func: FAIL" || echo "$func: OK"
}

check "reinterpret_cast"
check "std::exit"
check "std::abort"
check "std::terminate"
check "\.putback"
