#!/bin/sh

scp \
	src/apps/discovery/master-failure-test \
	src/apps/discovery/slave-failure-test \
	../scripts/benchmark-on-ant* \
	../scripts/benchmark-all* \
	MersenneTwister.dat \
	ant.apmath.spbu.ru:discovery/

#ssh ant.apmath.spbu.ru 'cd discovery; ./benchmark-on-ant'
